/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vacunasgrupo18.Vistas;

import java.awt.Color;
import javax.swing.JOptionPane;
import vacunasgrupo18.AccesoADatos.LaboratorioData;
import vacunasgrupo18.Entidades.Ciudadano;
import vacunasgrupo18.Entidades.Laboratorio;

/**
 *
 * @author lucia
 */
public class AgregarLaboratorio extends javax.swing.JInternalFrame {

    LaboratorioData labData = new LaboratorioData();
    Laboratorio labActual = null;
    
    public AgregarLaboratorio() {
        initComponents();
        setBounds(135, 5, 425, 425);
        this.getContentPane().setBackground(new Color(0, 153, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtCuit = new javax.swing.JTextField();
        jtNomLab = new javax.swing.JTextField();
        jtPais = new javax.swing.JTextField();
        jtDomCom = new javax.swing.JTextField();
        jbguardar = new javax.swing.JButton();
        jblimpiar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Registrar Laboratorio");

        jLabel2.setText("CUIT");

        jLabel3.setText("Nombre Laboratorio");

        jLabel4.setText("Pais de Origen");

        jLabel5.setText("Dominio Comercial");

        jbguardar.setText("Registrar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });

        jblimpiar.setText("Nuevo");
        jblimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimpiarActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jblimpiar)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbguardar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbBuscar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtDomCom, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(jtPais, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtNomLab, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtNomLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtDomCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbguardar)
                    .addComponent(jblimpiar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed
        
        try{
            
            Long cuit = Long.parseLong(jtCuit.getText());
            String nombre = jtNomLab.getText();
            String pais = jtPais.getText();
            String domCom = jtDomCom.getText();

        
        if(nombre.isEmpty() || pais.isEmpty() || domCom.isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Complete los campos obligatorios");
            return;
   
        }
        
        if(labActual == null){
            
            labActual = new Laboratorio(cuit, nombre, pais, domCom);
            labData.guardarLaboratorio(labActual);
            
        } else {
            
            labActual.setCuit(cuit);
            labActual.setNomLaboratorio(nombre);
            labActual.setPais(pais);
            labActual.setDomComercial(domCom);
            labData.modificarLaboratorio(labActual);
            
        }
        
        

        }catch(NumberFormatException ex){
            
            JOptionPane.showMessageDialog(this, "Debe ingresar un cuit valido");
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jblimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimpiarActionPerformed
       
        limpiarCampos();
        labActual = null;
        
    }//GEN-LAST:event_jblimpiarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        
        Long cuit = Long.parseLong(jtCuit.getText());
        
        labActual = labData.buscarLaboratorioPorCuit(cuit);
        
        if(labActual != null){
            
            jtNomLab.setText(labActual.getNomLaboratorio());
            jtDomCom.setText(labActual.getDomComercial());
            jtPais.setText(labActual.getPais());           
            
        }
        
    }//GEN-LAST:event_jbBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jblimpiar;
    private javax.swing.JTextField jtCuit;
    private javax.swing.JTextField jtDomCom;
    private javax.swing.JTextField jtNomLab;
    private javax.swing.JTextField jtPais;
    // End of variables declaration//GEN-END:variables

    public void limpiarCampos(){
        
        jtCuit.setText("");
        jtDomCom.setText("");
        jtNomLab.setText("");
        jtPais.setText("");
        
    }
    
}
